server:
  port: 8082
spring:
  application:
    name: fichaje
  config:
    import: optional:file:.env[.properties]
  mongodb:
    uri: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DB}