name: Build and test spring boot app
on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.actor }}/fichaje-springboot

jobs:
  build-test:
    uses: ./.github/workflows/build_test.yml

  build-push-image:
    needs: build-test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - name: Check out code
        uses: actions/checkout@v6

      - name: Login container registry
        run: docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          docker build . -t ${{ IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ IMAGE_NAME }}:latest
